# Generated by Django 4.2.11 on 2026-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesetting',
            options={'verbose_name': 'Game Setting', 'verbose_name_plural': 'Game Settings'},
        ),
        migrations.RemoveField(
            model_name='gamesetting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='gamesetting',
            name='value',
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='forced_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set a multiplier to force the next spin to land on it. It will be cleared after the spin.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
