# Generated by Django 4.2.11 on 2026-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamesetting_options_remove_gamesetting_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesetting',
            name='forced_multiplier',
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='demo_forced_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set a multiplier for DEMO mode (e.g., 2.5). Leave blank for random.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='live_forced_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set a multiplier for LIVE mode (e.g., 2.5). Leave blank for random.', max_digits=5, null=True),
        ),
    ]
