# Generated by Django 4.2.11 on 2026-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_gamesetting_forced_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesetting',
            name='demo_forced_multiplier',
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='demo_first',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multiplier for the FIRST demo spin (leave blank for random)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='demo_second',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multiplier for the SECOND demo spin (leave blank for random)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='demo_third',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multiplier for the THIRD demo spin (leave blank for random)', max_digits=5, null=True),
        ),
    ]
