# Generated by Django 4.2.11 on 2026-08-11 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odds', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potential_win', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betslips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_at_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_winner', models.BooleanField(blank=True, null=True)),
                ('betslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.betslip')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.match')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.odd')),
            ],
        ),
    ]
