# Generated by Django 4.2.11 on 2026-08-11 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_won', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('betslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.betslip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
